### ISSUE TITLE
Expression window closes as soon as I begin typing

### ISSUE THREAD

**Issue by Greymalkin** [j--wong/vscode-jmespath#3]
I just installed on my Mac (OS version 10.12.6).  When I activate the extension, as soon as I begin typing in the expression window, it closes.  I can get one character entered before it goes away, maybe two.

**Comment by Dagon-** [comment]
Just tried this out, get the same thing.
This is on 1.28.2

**Comment by Elektrolott** [comment]
Same here with VSCode 1.32.3 and JMESPath for VSCode 0.0.5

Any idea when this will be fixed?

**Comment by j--wong** [comment]
This issue has now been fixed in v0.0.6 (PR #4).  Please update your extension. Thanks
